# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: lskrauci <marvin@codam.nl>                   +#+                      #
#                                                    +#+                       #
#    Created: 2018/10/11 15:20:10 by lskrauci      #+#    #+#                  #
#    Updated: 2018/10/11 21:22:30 by lskrauci      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all: $(NAME)

$(NAME):
	gcc -o $(NAME) ft_display_file.c -Wall -Wextra -Werror

clean:
		rm -f *.o

fclean:	clean
		rm -f $(NAME)
