# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: lskrauci <marvin@codam.nl>                   +#+                      #
#                                                    +#+                       #
#    Created: 2018/10/11 17:04:55 by lskrauci      #+#    #+#                  #
#    Updated: 2018/10/11 21:20:01 by lskrauci      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME = ft_cat

all: $(NAME)

$(NAME):
	gcc -o $(NAME) ft_cat.c	-Wall -Wextra -Werror

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)
